### ISSUE TITLE
Sentinel file is always created (even if initialization fails)

### ISSUE THREAD

**Issue by jeffadair** [Senzing/docker-mysql-init#3]
**Describe the bug**
Sentinel file gets created even if initialization fails.

**To Reproduce**
Mess up your env varibles in a way that the mysql command fails, like point SENZING_DIR at the wrong location.

**Expected behavior**
Sentinel file only gets created when initialization succeeds.

**Desktop (please complete the following information):**

- OS: CentOS 7

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/docker-mysql-init/pull/4
